spring:
  profiles:
    active: ${APP_VERSION}
  application:
    name: service-registry

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

server:
  port: 8761